DROP TABLE IF EXISTS FOODS;

CREATE TABLE FOODS(

	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	calories INTEGER NOT NULL,
	brand VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);